# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35df3b91c49cc31456ee32b09e6c61563989c106faa84868d974c364130c68b54f7a39df7f11fff5fad11150e2a3cf6b2703e82195c042ed3c6185ad2b3f1805

test:
  secret_key_base: 60b853454a37442c2c1d99c8aa9afc3b86fe3c9cec68a685c092dce93920bd30ad35f0f34ccc8200363f4ba3ae4ba5470b2e27b34dbf1ead199466e6c93c12fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
